spring.application.name=realEstateCheck

server.port=8082

public-data.api.base-url=https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade
public-data.api.service-key=5fd1de04e9d24ffefe3290c48fc7ba51273bf056c06cb8619c45f4787c95a581
